micronaut:
  application:
    name: nortluCardapioApi
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'unisenha'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
    packages-to-scan:
      - 'io.github.pasteleiros.nortlulib.entity'
redis.uri: redis://10.5.0.2
