CREATE TABLE endereco (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bairro varchar(255) NULL,
	cep varchar(255) NULL,
	cidade varchar(255) NULL,
	complemento varchar(255) NULL,
	logradouro varchar(255) NULL,
	numero int4 NOT NULL,
	observacao varchar(255) NULL,
	CONSTRAINT pk_endereco PRIMARY KEY (id)
);