
CREATE TABLE pedido (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_forma_pagamento int8 NOT NULL,
	valor_total numeric(19,2) NULL,
	id_usuario int8 NULL,
	CONSTRAINT pk_pedido PRIMARY KEY (id),
	CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);