CREATE TABLE produto (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NULL,
	descricao varchar(255) NULL,
	id_categoria int NULL,
	valor varchar(255) NULL,
	foto varchar(255) NULL,
	CONSTRAINT pk_produto PRIMARY KEY (id)
);